CREATE TABLE features (
    clientid character varying(255),
    meangoogframerateinput integer,
    icerestart boolean,
    meangoogcurrentdelayms integer,
    usingicelite boolean,
    isinitiator boolean,
    browsertype character varying(255),
    mingoogframeratereceived integer,
    numberofcandidatepairchanges integer,
    mediatypes character varying(255),
    modegoogframerateoutput integer,
    browsernameversion character varying(255),
    configuredrtcpmuxpolicy boolean,
    usingrtcpmux boolean,
    icefailuresubsequent boolean,
    maxgoogframerateinput integer,
    maxgoogminplayoutdelayms integer,
    meangoogtargetdelayms integer,
    meangoogjitterbufferms integer,
    maxgoogframeratesent integer,
    meangoogframeratesent integer,
    gatheredturntcp boolean,
    mingoogminplayoutdelayms integer,
    signalingstableatleastonce boolean,
    maxgoogframeheightinput integer,
    modegoogframeratereceived integer,
    modegoogframewidthsent integer,
    maxgoogframewidthsent integer,
    configuredwithiceservers boolean,
    maxstreams integer,
    maxgoogtargetdelayms integer,
    hadremoteturncandidate boolean,
    browsernameversionos character varying(255),
    peerconnectionsetdescriptionfailure boolean,
    gatheredturnudp boolean,
    meangoogminplayoutdelayms integer,
    configuredbundlepolicy boolean,
    mingoogframewidthinput integer,
    maxgoogjitterbufferms integer,
    statsmeanreceivingbitrate integer,
    localcreatedelay integer,
    maxgoogframeheightsent integer,
    iceconnectedorcompleted boolean,
    modegoogframerateinput integer,
    maxgoogframewidthinput integer,
    maxgoogframeratereceived integer,
    browserversion character varying(255),
    modegoogframewidthinput integer,
    meangoogframeheightinput integer,
    modegoogframeheightreceived integer,
    calledlegacygetusermedia boolean,
    icefailure boolean,
    calledgetusermediarequestingscreen boolean,
    statsmeanroundtriptime integer,
    mingoogframeheightreceived integer,
    meangoogframerateoutput integer,
    calledmediadevicesgetusermedia boolean,
    mingoogcurrentdelayms integer,
    maxgoogframeheightreceived integer,
    usingmultistream boolean,
    mingoogframeratesent integer,
    calledgetusermediarequestingvideo boolean,
    meangoogframeheightsent integer,
    usingbundle boolean,
    gatheringtime integer,
    getusermediasuccess boolean,
    gatheredturntls boolean,
    peerconnectionaddicecandidatefailure boolean,
    configuredicetransportpolicy boolean,
    mingoogframerateoutput integer,
    configured boolean,
    mingoogframewidthsent integer,
    statsmeansendingbitrate integer,
    calledgetusermedia boolean,
    datetime bigint,
    numberofremoteicecandidates integer,
    modegoogframewidthreceived integer,
    modegoogframeratesent integer,
    meangoogframewidthsent integer,
    modegoogframeheightinput integer,
    pageurl character varying(255),
    date bigint,
    icegatheringcomplete boolean,
    gatheredstun boolean,
    meangoogframewidthinput integer,
    meangoogframeheightreceived integer,
    mingoogjitterbufferms integer,
    maxgoogframewidthreceived integer,
    browseros character varying(255),
    mingoogframerateinput integer,
    modegoogframeheightsent integer,
    meangoogframewidthreceived integer,
    mingoogframewidthreceived integer,
    mingoogtargetdelayms integer,
    sessionduration integer,
    statsmeanaudiolevel real,
    configuredcertificate boolean,
    connectiontime integer,
    calledgetusermediarequestingaudio boolean,
    browsername character varying(255),
    maxgoogframerateoutput integer,
    meangoogframeratereceived integer,
    numberoflocalicecandidates integer,
    mingoogframeheightsent integer,
    getusermediasuccessnotreally boolean,
    wasgoogbandwidthlimitedresolutionever boolean,
    maxgoogcurrentdelayms integer,
    connectionid character varying(255) DEFAULT ''::character varying NOT NULL,
    getusermediaerror character varying(255),
    firstcandidatepairtype character varying(255),
    firstaudiotracklabel character varying(255),
    firstvideotracklabel character varying(255)
);
