CREATE TABLE features_import (
    browsermajorversion character varying(255),
    browsername character varying(255),
    browsernameos character varying(255),
    browsernameversion character varying(255),
    browsernameversionos character varying(255),
    browseros character varying(255),
    browsertype character varying(255),
    browserversion character varying(255),
    bweGoogActualEncBitrateMean: integer,
    bweGoogActualEncBitrateMax: integer,
    bweGoogActualEncBitrateMin: integer,
    bweGoogActualEncBitrateVariance: integer,
    bweGoogActualEncBitrateSkewness: integer,
    bweGoogActualEncBitrateKurtosis: integer,
    bweGoogRetransmitBitrateMean: integer,
    bweGoogRetransmitBitrateMax: integer,
    bweGoogRetransmitBitrateMin: integer,
    bweGoogRetransmitBitrateVariance: integer,
    bweGoogRetransmitBitrateSkewness: integer,
    bweGoogRetransmitBitrateKurtosis: integer,
    bweGoogTargetEncBitrateMean: integer,
    bweGoogTargetEncBitrateMax: integer,
    bweGoogTargetEncBitrateMin: integer,
    bweGoogTargetEncBitrateVariance: integer,
    bweGoogTargetEncBitrateSkewness: integer,
    bweGoogTargetEncBitrateKurtosis: integer,
    bweGoogBucketDelayMean: integer,
    bweGoogBucketDelayMax: integer,
    bweGoogBucketDelayMin: integer,
    bweGoogBucketDelayVariance: integer,
    bweGoogBucketDelaySkewness: integer,
    bweGoogBucketDelayKurtosis: integer,
    bweGoogTransmitBitrateMean: integer,
    bweGoogTransmitBitrateMax: integer,
    bweGoogTransmitBitrateMin: integer,
    bweGoogTransmitBitrateVariance: integer,
    bweGoogTransmitBitrateSkewness: integer,
    bweGoogTransmitBitrateKurtosis: integer,
    bweAvailableOutgoingBitrateMean: integer,
    bweAvailableOutgoingBitrateMax: integer,
    bweAvailableOutgoingBitrateMin: integer,
    bweAvailableOutgoingBitrateVariance: integer,
    bweAvailableOutgoingBitrateSkewness: integer,
    bweAvailableOutgoingBitrateKurtosis: integer,
    bweAvailableIncomingBitrateMean: integer,
    bweAvailableIncomingBitrateMax: integer,
    bweAvailableIncomingBitrateMin: integer,
    bweAvailableIncomingBitrateVariance: integer,
    bweAvailableIncomingBitrateSkewness: integer,
    bweAvailableIncomingBitrateKurtosis: integer,
    calledgetusermedia boolean,
    calledgetusermediarequestingaudio boolean,
    calledgetusermediarequestingscreen character varying(255),
    calledgetusermediarequestingvideo boolean,
    calledlegacygetusermedia boolean,
    calledmediadevicesgetusermedia boolean,
    clientid character varying(255),
    clientidentifier character varying(255),
    conferenceIdentifier character varying(255),
    configured boolean,
    configuredbundlepolicy boolean,
    configuredcertificate boolean,
    configuredicetransportpolicy boolean,
    configuredrtcpmuxpolicy boolean,
    configuredwithiceservers boolean,
    configuredWithSTUN boolean,
    configuredWithTURN boolean,
    configuredWithTURNTCP boolean,
    configuredWithTURNTLS boolean,
    configuredWithTURNUDP boolean,
    connectionid character varying(255) DEFAULT ''::character varying NOT NULL,
    connectiontime integer,
    date bigint,
    datetime bigint,
    dtlsCipherSuite character varying(255),
    firstaudiotracklabel character varying(255),
    firstcandidatepairtype character varying(255),
    firstcandidatepairlocaltype: character varying(255),
    firstcandidatepairremotetype: character varying(255),
    firstcandidatepairlocalipaddress: character varying(255),
    firstcandidatepairremoteipaddress: character varying(255),
    firstcandidatepairlocaltypepreference: integer,
    firstcandidatepairremotetypepreference: integer,
    firstvideotracklabel character varying(255),
    gatheredhost boolean,
    gatheredstun boolean,
    gatheredturntcp boolean,
    gatheredturntls boolean,
    gatheredturnudp boolean,
    gatheredrfc1918addressPrefix16 boolean,
    gatheredrfc1918addressPrefix12 boolean,
    gatheredrfc1918addressPrefix10 boolean,
    gatheringtime integer,
    gatheringtimeturntcp integer,
    gatheringtimeturntls integer,
    gatheringtimeturnudp integer,
    getusermediaerror character varying(255),
    getusermediasuccess boolean,
    getusermediasuccessnotreally boolean,
    hadremoteturncandidate boolean,
    iceconnectedorcompleted boolean,
    icefailure boolean,
    icefailuresubsequent boolean,
    icegatheringcomplete boolean,
    icerestart boolean,
    isinitiator boolean,
    localcreatedelay integer,
    maxaudiogoogjitterbufferms integer,
    maxaudiogoogjitterreceived integer,
    maxaudiogoogpreferredjitterbufferms integer,
    maxgoogcurrentdelayms integer,
    maxgoogframeheightinput integer,
    maxgoogframeheightreceived integer,
    maxgoogframeheightsent integer,
    maxgoogframerateinput integer,
    maxgoogframerateoutput integer,
    maxgoogframeratereceived integer,
    maxgoogframeratesent integer,
    maxgoogframewidthinput integer,
    maxgoogframewidthreceived integer,
    maxgoogframewidthsent integer,
    maxgoogjitterbufferms integer,
    maxgoogminplayoutdelayms integer,
    maxgoogtargetdelayms integer,
    maxstreams integer,
    meanaudiogoogjitterbufferms integer,
    meanaudiogoogjitterreceived integer,
    meanaudiogoogpreferredjitterbufferms integer,
    meangoogcurrentdelayms integer,
    meangoogframeheightinput integer,
    meangoogframeheightreceived integer,
    meangoogframeheightsent integer,
    meangoogframerateinput integer,
    meangoogframerateoutput integer,
    meangoogframeratereceived integer,
    meangoogframeratesent integer,
    meangoogframewidthinput integer,
    meangoogframewidthreceived integer,
    meangoogframewidthsent integer,
    meangoogjitterbufferms integer,
    meangoogminplayoutdelayms integer,
    meangoogtargetdelayms integer,
    mediatypes character varying(255),
    minaudiogoogjitterbufferms integer,
    minaudiogoogjitterreceived integer,
    minaudiogoogpreferredjitterbufferms integer,
    mingoogcurrentdelayms integer,
    mingoogframeheightinput integer,
    mingoogframeheightreceived integer,
    mingoogframeheightsent integer,
    mingoogframerateinput integer,
    mingoogframerateoutput integer,
    mingoogframeratereceived integer,
    mingoogframeratesent integer,
    mingoogframewidthinput integer,
    mingoogframewidthreceived integer,
    mingoogframewidthsent integer,
    mingoogjitterbufferms integer,
    mingoogminplayoutdelayms integer,
    mingoogtargetdelayms integer,
    modegoogframeheightinput integer,
    modegoogframeheightreceived integer,
    modegoogframeheightsent integer,
    modegoogframerateinput integer,
    modegoogframerateoutput integer,
    modegoogframeratereceived integer,
    modegoogframeratesent integer,
    modegoogframewidthinput integer,
    modegoogframewidthreceived integer,
    modegoogframewidthsent integer,
    numberofcandidatepairchanges integer,
    numberoflocalicecandidates integer,
    numberofremoteicecandidates integer,
    numberofpeerconnections integer,
    pageurl character varying(255),
    origin character varying(255),
    peerconnectionaddicecandidatefailure boolean,
    peerconnectionsetdescriptionfailure boolean,
    peeridentifier character varying(255),
    recvaudiocodec character varying(255),
    recvvideocodec character varying(255),
    remotetype character varying(255),
    sendaudiocodec character varying(255),
    sendvideocodec character varying(255),
    sendAudioRTTNeverGreaterZero boolean,
    sessionduration integer,
    signalingstableatleastonce boolean,
    srtpCipherSuite character varying(255),
    statsmeanaudiolevel real,
    statsmeanreceivingbitrate integer,
    statsmeanroundtriptime integer,
    statsmeansendingbitrate integer,
    timeBetweenGetUserMediaAndGetUserMediaSuccess integer,
    timeBetweenGetUserMediaAndGetUserMediaFailure integer,
    timebetweensetlocaldescriptionandonicecandidate integer,
    timebetweensetremotedescriptionandaddicecandidate integer,
    usingbundle boolean,
    usingicelite boolean,
    usingmultistream boolean,
    usingrtcpmux boolean,
    wasgoogbandwidthlimitedresolutionevertrue boolean,
    wasgoogCpuLimitedResolutionevertrue boolean,
    audioSendAudioLevelMean: integer,
    audioSendAudioLevelMax: integer,
    audioSendAudioLevelMin: integer,
    audioSendAudioLevelVariance: integer,
    audioSendAudioLevelSkewness: integer,
    audioSendAudioLevelKurtosis: integer,
    audioSendGoogJitterReceivedMean: integer,
    audioSendGoogJitterReceivedMax: integer,
    audioSendGoogJitterReceivedMin: integer,
    audioSendGoogJitterReceivedVariance: integer,
    audioSendGoogJitterReceivedSkewness: integer,
    audioSendGoogJitterReceivedKurtosis: integer,
    audioSendGoogRttMean: integer,
    audioSendGoogRttMax: integer,
    audioSendGoogRttMin: integer,
    audioSendGoogRttVariance: integer,
    audioSendGoogRttSkewness: integer,
    audioSendGoogRttKurtosis: integer,
    audioRecvAudioLevelMean: integer,
    audioRecvAudioLevelMax: integer,
    audioRecvAudioLevelMin: integer,
    audioRecvAudioLevelVariance: integer,
    audioRecvAudioLevelSkewness: integer,
    audioRecvAudioLevelKurtosis: integer,
    audioRecvGoogJitterReceivedMean: integer,
    audioRecvGoogJitterReceivedMax: integer,
    audioRecvGoogJitterReceivedMin: integer,
    audioRecvGoogJitterReceivedVariance: integer,
    audioRecvGoogJitterReceivedSkewness: integer,
    audioRecvGoogJitterReceivedKurtosis: integer,
    audioRecvGoogCurrentDelayMsMean: integer,
    audioRecvGoogCurrentDelayMsMax: integer,
    audioRecvGoogCurrentDelayMsMin: integer,
    audioRecvGoogCurrentDelayMsVariance: integer,
    audioRecvGoogCurrentDelayMsSkewness: integer,
    audioRecvGoogCurrentDelayMsKurtosis: integer,
    audioRecvGoogJitterBufferMsMean: integer,
    audioRecvGoogJitterBufferMsMax: integer,
    audioRecvGoogJitterBufferMsMin: integer,
    audioRecvGoogJitterBufferMsVariance: integer,
    audioRecvGoogJitterBufferMsSkewness: integer,
    audioRecvGoogJitterBufferMsKurtosis: integer,
    audioRecvGoogPreferredJitterBufferMsMean: integer,
    audioRecvGoogPreferredJitterBufferMsMax: integer,
    audioRecvGoogPreferredJitterBufferMsMin: integer,
    audioRecvGoogPreferredJitterBufferMsVariance: integer,
    audioRecvGoogPreferredJitterBufferMsSkewness: integer,
    audioRecvGoogPreferredJitterBufferMsKurtosis: integer,
    videoSendGoogRttMean: integer,
    videoSendGoogRttMax: integer,
    videoSendGoogRttMin: integer,
    videoSendGoogRttVariance: integer,
    videoSendGoogRttSkewness: integer,
    videoSendGoogRttKurtosis: integer,
    videoSendGoogEncodeUsagePercentMean: integer,
    videoSendGoogEncodeUsagePercentMax: integer,
    videoSendGoogEncodeUsagePercentMin: integer,
    videoSendGoogEncodeUsagePercentVariance: integer,
    videoSendGoogEncodeUsagePercentSkewness: integer,
    videoSendGoogEncodeUsagePercentKurtosis: integer,
    videoSendGoogFrameHeightInputMax: integer,
    videoSendGoogFrameHeightInputMin: integer,
    videoSendGoogFrameHeightInputMode: integer,
    videoSendGoogFrameHeightSentMax: integer,
    videoSendGoogFrameHeightSentMin: integer,
    videoSendGoogFrameHeightSentMode: integer,
    videoSendGoogFrameWidthInputMax: integer,
    videoSendGoogFrameWidthInputMin: integer,
    videoSendGoogFrameWidthInputMode: integer,
    videoSendGoogFrameWidthSentMax: integer,
    videoSendGoogFrameWidthSentMin: integer,
    videoSendGoogFrameWidthSentMode: integer,
    videoSendGoogCpuLimitedResolutionMean: integer,
    videoSendGoogCpuLimitedResolutionMax: integer,
    videoSendGoogCpuLimitedResolutionMin: integer,
    videoSendGoogCpuLimitedResolutionMode: integer,
    videoSendGoogBandwidthLimitedResolutionMean: integer,
    videoSendGoogBandwidthLimitedResolutionMax: integer,
    videoSendGoogBandwidthLimitedResolutionMin: integer,
    videoSendGoogBandwidthLimitedResolutionMode: integer,
    videoRecvGoogCurrentDelayMsMean: integer,
    videoRecvGoogCurrentDelayMsMax: integer,
    videoRecvGoogCurrentDelayMsMin: integer,
    videoRecvGoogCurrentDelayMsVariance: integer,
    videoRecvGoogCurrentDelayMsSkewness: integer,
    videoRecvGoogCurrentDelayMsKurtosis: integer,
    videoRecvGoogJitterBufferMsMean: integer,
    videoRecvGoogJitterBufferMsMax: integer,
    videoRecvGoogJitterBufferMsMin: integer,
    videoRecvGoogJitterBufferMsVariance: integer,
    videoRecvGoogJitterBufferMsSkewness: integer,
    videoRecvGoogJitterBufferMsKurtosis: integer,
    videoRecvGoogDecodeMsMean: integer,
    videoRecvGoogDecodeMsMax: integer,
    videoRecvGoogDecodeMsMin: integer,
    videoRecvGoogDecodeMsVariance: integer,
    videoRecvGoogDecodeMsSkewness: integer,
    videoRecvGoogDecodeMsKurtosis: integer,
    videoRecvGoogMaxDecodeMsMean: integer,
    videoRecvGoogMaxDecodeMsMax: integer,
    videoRecvGoogMaxDecodeMsMin: integer,
    videoRecvGoogMaxDecodeMsVariance: integer,
    videoRecvGoogMaxDecodeMsSkewness: integer,
    videoRecvGoogMaxDecodeMsKurtosis: integer,
    videoRecvGoogMinPlayoutDelayMsMean: integer,
    videoRecvGoogMinPlayoutDelayMsMax: integer,
    videoRecvGoogMinPlayoutDelayMsMin: integer,
    videoRecvGoogMinPlayoutDelayMsVariance: integer,
    videoRecvGoogMinPlayoutDelayMsSkewness: integer,
    videoRecvGoogMinPlayoutDelayMsKurtosis: integer,
    videoRecvGoogRenderDelayMsMean: integer,
    videoRecvGoogRenderDelayMsMax: integer,
    videoRecvGoogRenderDelayMsMin: integer,
    videoRecvGoogRenderDelayMsVariance: integer,
    videoRecvGoogRenderDelayMsSkewness: integer,
    videoRecvGoogRenderDelayMsKurtosis: integer,
    videoRecvGoogTargetDelayMsMean: integer,
    videoRecvGoogTargetDelayMsMax: integer,
    videoRecvGoogTargetDelayMsMin: integer,
    videoRecvGoogTargetDelayMsVariance: integer,
    videoRecvGoogTargetDelayMsSkewness: integer,
    videoRecvGoogTargetDelayMsKurtosis: integer,
    videoRecvGoogFrameHeightReceivedMax: integer,
    videoRecvGoogFrameHeightReceivedMin: integer,
    videoRecvGoogFrameHeightReceivedMode: integer,
    videoRecvGoogFrameWidthReceivedMax: integer,
    videoRecvGoogFrameWidthReceivedMin: integer,
    videoRecvGoogFrameWidthReceivedMode: integer
);
